quiz2/config/routes.rb
Rails.application.routes.draw do

  root "requests#index"
  resources :requests
  get '/requests/flop/:id' => 'requests#flop', as: :request_flop

end

quiz2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

quiz2/app/models/request.rb
class Request < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true

  before_validation :set_status_default

  def self.search(keyword)
    where(["name ILIKE ? OR email ILIKE ? OR department ILIKE ? OR message ILIKE ?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  end

  private

  def set_status_default
    self.status ||= false
  end
end

quiz2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

quiz2/app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  before_action :find_request, only: [:show, :edit, :flop, :update, :destroy]

  REQUEST_PER_PAGE = 7

  def new

    @request = Request.new

  end

  def create

    @request        = Request.new request_params

    if @request.save
      redirect_to request_path(@request), notice: "Request created successfully"
    else
      render :new
    end
  end

  def show
  end

  def index

    @search = Request.search(params[:query])
    @requests = @search.order(status: :asc, id: :desc).
                          page(params[:page]).
                          per(REQUEST_PER_PAGE)
  end

  def flop
    @request = Request.find(params[:id])
    @request.status = !@request.status
    @request.save!
    redirect_to requests_path
  end

  def edit
  end

  def update
    if @request.update request_params
      redirect_to request_path(@request)
    else
      render :edit
    end
  end

  def destroy
    @request.destroy
    redirect_to requests_path
  end

  private
  def find_request
    @request = Request.find params[:id]
  end

  def request_params
    params.require(:request).permit([:name, :email, :department, :message])
  end

  # def self.search(keyword)
  #   where(["name ILIKE ? OR email ILIKE ? OR department ILIKE ? OR message ILIKE ?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
  # end


end

quiz2/app/helpers/application_helper.rb
module ApplicationHelper
end

quiz2/app/helpers/requests_helper.rb
module RequestsHelper
end

quiz2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "New Request", new_request_path %>
    |
    <%= link_to "Requests", requests_path %>
    <hr>
    <div class="flash-message">
      <%= flash[:notice] || flash[:alert] %>
    </div>

    <!-- <div>
      <%# f.label :self.search%>
      <%# f.text_area :self.search %>
    </div> -->
    <!-- <%# f.submit %> -->

    <%= yield %>
  </body>
</html>

quiz2/app/views/requests/_form.html.erb
<%# @request.errors.full_messages.join(", ") %>
<%= form_for @request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.radio_button :department, "Sales" %>
    <%= f.label :department, "Sales", :value => "Sales" %>
    <%= f.radio_button :department, "Marketing" %>
    <%= f.label :department, "Marketing", :value => "Marketing" %>
    <%= f.radio_button :department, "Technical" %>
    <%= f.label :department, "Technical", :value => "Technical" %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit %>
<% end %>

quiz2/app/views/requests/edit.html.erb
<h1>Edit Request</h1>
<%= render "form" %>

quiz2/app/views/requests/index.html.erb
<h1>Support Requests</h1>
<!-- <% @requests.each do |req| %>
<%= link_to req.name, request_path(req)%>
<hr>
<% end %> -->

<div class="col-sm-3 col-md-3 search-bar">
    <%= form_tag requests_path, method: 'get', class: 'navbar-form navbar-left', role: 'search' do %>
      <div class='input-group'>
        <%= text_field_tag :query, params[:query], size: 150, placeholder: "Search", class: "form-control"%>
        <div class='input-group-btn'>
          <%= submit_tag'Submit' %>
        </div>
      </div>
    <% end %>
  </div>

<table border="1" width="50%">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th>Actions</th>
  </tr>


  <tr>
    <% @requests.each do |req| %>
       <td><%= req.name %></td>
       <td><%= req.email %></td>
       <td><%= req.department %></td>
       <td><%= req.message %></td>
       <td><%= link_to "Edit", edit_request_path(req) %>
           <%= link_to "Delete", request_path(req), method: :delete,
           data: {confirm: "Are you sure you want to delete this request?"} %>
          <%= link_to(req.status ? "Undone" : "Done", request_flop_path(req)) %> </td>
  </tr>
     <% end %>
</table>

  <%= paginate @requests %>

quiz2/app/views/requests/new.html.erb
<h1>New Request</h1>
<%# render "form" %>

<%= @request.errors.full_messages.join(", ") %>
<%= form_for @request do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div>
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<div>
    <%= f.radio_button :department, "Sales" %>
    <%= f.label :department, "Sales", :value => "Sales" %>
    <%= f.radio_button :department, "Marketing" %>
    <%= f.label :department, "Marketing", :value => "Marketing" %>
    <%= f.radio_button :department, "Technical" %>
    <%= f.label :department, "Technical", :value => "Technical" %>
  </div>
<div>
  <%= f.label :message %>
  <%= f.text_area :message %>
</div>

<%= f.submit %>

<% end %>

quiz2/app/views/requests/show.html.erb
<table border="1" width="50%">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th>Actions</th>
  </tr>

  <tr>
    <td>
      <%=  @request.name %>
    </td>

    <td>
      <%= @request.email%>
    </td>

    <td>
      <%= @request.department%>
    </td>

    <td>
      <%= @request.message%>
    </td>

    <td><%= link_to "Edit", edit_request_path(@request) %>
        <%= link_to "Delete", request_path(@request), method: :delete,
        data: {confirm: "Are you sure you want to delete this request?"} %>
    </td>

  </tr>